In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix

from sklearn.neighbors import NearestNeighbors
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score

In [3]:
file1 = open("../data/communities.names", "r+")
lines = file1.readlines()
file1.close() 

In [3]:
lines2 = lines[75:(75+128)]
lines2 = [str(i).replace('\n','').replace('@attribute','').strip() for i in lines2]

In [77]:
path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/communities/communities.data'
df = pd.read_csv(path, index_col=False,names=lines2)

In [5]:
y = df['ViolentCrimesPerPop numeric']
X = df.drop(columns=['ViolentCrimesPerPop numeric'],axis=1)

In [6]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1994 entries, 0 to 1993
Columns: 127 entries, state numeric to PolicBudgPerPop numeric
dtypes: float64(99), int64(2), object(26)
memory usage: 1.9+ MB


In [7]:
#X.select_dtypes(np.number)

In [8]:
#X['community numeric'].value_counts()

In [9]:
#sns.heatmap(X.corr())

# Adult Dataset

In [5]:
path = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'
columns= ['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','over50']
train_set = pd.read_csv(path, index_col=False,names=columns)

In [6]:
path_test = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test'
test_set = pd.read_csv(path_test,skiprows=1, index_col=False,names=columns)

In [7]:
train_set.shape

(32561, 15)

In [8]:
test_set

age      workclass  fnlwgt      education  education-num  \
0       25        Private  226802           11th              7   
1       38        Private   89814        HS-grad              9   
2       28      Local-gov  336951     Assoc-acdm             12   
3       44        Private  160323   Some-college             10   
4       18              ?  103497   Some-college             10   
...    ...            ...     ...            ...            ...   
16276   39        Private  215419      Bachelors             13   
16277   64              ?  321403        HS-grad              9   
16278   38        Private  374983      Bachelors             13   
16279   44        Private   83891      Bachelors             13   
16280   35   Self-emp-inc  182148      Bachelors             13   

            marital-status          occupation     relationship  \
0            Never-married   Machine-op-inspct        Own-child   
1       Married-civ-spouse     Farming-fishing          Husband   
2       Married-civ-spouse     Protective-serv          Husband   
3       Married-civ-spouse   Machine-op-inspct          Husband   
4            Never-married                   ?        Own-child   
...                    ...                 ...              ...   
16276             Divorced      Prof-specialty    Not-in-family   
16277              Widowed                   ?   Other-relative   
16278   Married-civ-spouse      Prof-specialty          Husband   
16279             Divorced        Adm-clerical        Own-child   
16280   Married-civ-spouse     Exec-managerial          Husband   

                      race      sex  capital-gain  capital-loss  \
0                    Black     Male             0             0   
1                    White     Male             0             0   
2                    White     Male             0             0   
3                    Black     Male          7688             0   
4                    White   Female             0             0   
...                    ...      ...           ...           ...   
16276                White   Female             0             0   
16277                Black     Male             0             0   
16278                White     Male             0             0   
16279   Asian-Pac-Islander     Male          5455             0   
16280                White     Male             0             0   

       hours-per-week  native-country   over50  
0                  40   United-States   <=50K.  
1                  50   United-States   <=50K.  
2                  40   United-States    >50K.  
3                  40   United-States    >50K.  
4                  30   United-States   <=50K.  
...               ...             ...      ...  
16276              36   United-States   <=50K.  
16277              40   United-States   <=50K.  
16278              50   United-States   <=50K.  
16279              40   United-States   <=50K.  
16280              60   United-States    >50K.  

[16281 rows x 15 columns]

In [9]:
data = pd.concat([train_set,test_set])

In [10]:
data.iloc[train_set.shape[0]:,:]

age      workclass  fnlwgt      education  education-num  \
0       25        Private  226802           11th              7   
1       38        Private   89814        HS-grad              9   
2       28      Local-gov  336951     Assoc-acdm             12   
3       44        Private  160323   Some-college             10   
4       18              ?  103497   Some-college             10   
...    ...            ...     ...            ...            ...   
16276   39        Private  215419      Bachelors             13   
16277   64              ?  321403        HS-grad              9   
16278   38        Private  374983      Bachelors             13   
16279   44        Private   83891      Bachelors             13   
16280   35   Self-emp-inc  182148      Bachelors             13   

            marital-status          occupation     relationship  \
0            Never-married   Machine-op-inspct        Own-child   
1       Married-civ-spouse     Farming-fishing          Husband   
2       Married-civ-spouse     Protective-serv          Husband   
3       Married-civ-spouse   Machine-op-inspct          Husband   
4            Never-married                   ?        Own-child   
...                    ...                 ...              ...   
16276             Divorced      Prof-specialty    Not-in-family   
16277              Widowed                   ?   Other-relative   
16278   Married-civ-spouse      Prof-specialty          Husband   
16279             Divorced        Adm-clerical        Own-child   
16280   Married-civ-spouse     Exec-managerial          Husband   

                      race      sex  capital-gain  capital-loss  \
0                    Black     Male             0             0   
1                    White     Male             0             0   
2                    White     Male             0             0   
3                    Black     Male          7688             0   
4                    White   Female             0             0   
...                    ...      ...           ...           ...   
16276                White   Female             0             0   
16277                Black     Male             0             0   
16278                White     Male             0             0   
16279   Asian-Pac-Islander     Male          5455             0   
16280                White     Male             0             0   

       hours-per-week  native-country   over50  
0                  40   United-States   <=50K.  
1                  50   United-States   <=50K.  
2                  40   United-States    >50K.  
3                  40   United-States    >50K.  
4                  30   United-States   <=50K.  
...               ...             ...      ...  
16276              36   United-States   <=50K.  
16277              40   United-States   <=50K.  
16278              50   United-States   <=50K.  
16279              40   United-States   <=50K.  
16280              60   United-States    >50K.  

[16281 rows x 15 columns]

In [11]:
test_set.shape

(16281, 15)

In [12]:
data['sex'] = data['sex'].str.strip()

In [13]:
data['race'] = data['race'].str.strip()

In [14]:
data['native-country'] = data['native-country'].str.strip()

In [15]:
data['over50'] = data['over50'].str.strip().str.replace('.','')

C:\Users\Beate\AppData\Local\Temp\ipykernel_14160\3815454752.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['over50'] = data['over50'].str.strip().str.replace('.','')


In [16]:
data['target'] = data['over50'].apply(lambda x: 1 if x == '>50K' else 0)

In [17]:
data['over50']

0        <=50K
1        <=50K
2        <=50K
3        <=50K
4        <=50K
         ...  
16276    <=50K
16277    <=50K
16278    <=50K
16279    <=50K
16280     >50K
Name: over50, Length: 48842, dtype: object

In [18]:
data['target']

0        0
1        0
2        0
3        0
4        0
        ..
16276    0
16277    0
16278    0
16279    0
16280    1
Name: target, Length: 48842, dtype: int64

In [19]:
data.drop(columns=['over50'],axis=1,inplace=True)

In [20]:
data2 = pd.get_dummies(data,drop_first=True)

In [21]:
data2.columns = [ str(i).strip().replace(' ','') for i in data2.columns]

In [22]:
#data2['over50_>50K'].sum()/data2.shape[0]

In [23]:
train = data2.iloc[:train_set.shape[0],:]
test = data2.iloc[train_set.shape[0]:,:]

In [24]:
train.shape

(32561, 101)

In [25]:
test.shape

(16281, 101)

In [26]:
y_train = train['target']
X_train = train.drop(columns=['target'],axis=1)
y_test = test['target']
X_test = test.drop(columns=['target'],axis=1)

In [27]:
y_train = y_train.to_numpy().ravel()

In [28]:
X_train.shape

(32561, 100)

In [29]:
y_train.shape

(32561,)

In [30]:
y_train.sum()

7841

In [31]:
data['sex'].value_counts()

Male      32650
Female    16192
Name: sex, dtype: int64

In [32]:
data['race'].value_counts()

White                 41762
Black                  4685
Asian-Pac-Islander     1519
Amer-Indian-Eskimo      470
Other                   406
Name: race, dtype: int64

In [33]:
data['native-country'].value_counts()

United-States                 43832
Mexico                          951
?                               857
Philippines                     295
Germany                         206
Puerto-Rico                     184
Canada                          182
El-Salvador                     155
India                           151
Cuba                            138
England                         127
China                           122
South                           115
Jamaica                         106
Italy                           105
Dominican-Republic              103
Japan                            92
Guatemala                        88
Poland                           87
Vietnam                          86
Columbia                         85
Haiti                            75
Portugal                         67
Taiwan                           65
Iran                             59
Greece                           49
Nicaragua                        49
Peru                        

In [34]:
data['workclass'].value_counts()

 Private             33906
 Self-emp-not-inc     3862
 Local-gov            3136
 ?                    2799
 State-gov            1981
 Self-emp-inc         1695
 Federal-gov          1432
 Without-pay            21
 Never-worked           10
Name: workclass, dtype: int64

## Absolute measures

### Impact ratio

$$r = \frac{p(y^{+}|s^{1})}{p(y^{+}|s^{0})}$$

Protected group: Female  
General group: Male

In [35]:
def impact_ratio(column,protected,general):
    prot = data[data[column] == protected]
    gen = data[data[column] == general]
    p_f = prot['target'].sum()/prot.shape[0]
    p_m = gen['target'].sum()/gen.shape[0]
    ratio = p_f/p_m
    return  ratio, (1/ratio)

In [36]:
p_f = data[data['sex'] == 'Female']['target'].sum()/data[data['sex'] == 'Female'].shape[0]
p_m = data[data['sex'] == 'Male']['target'].sum()/data[data['sex'] == 'Male'].shape[0]
print(p_f)
print(p_m)

0.10925148221343874
0.3037672281776417


In [37]:
ratio = p_f/p_m

In [38]:
print(ratio)
print(1/ratio)

0.3596552625800337
2.7804403384128737


In [39]:
impact_ratio('sex','Female','Male')

(0.3596552625800337, 2.7804403384128737)

Protected group: Black  
General group: White

In [40]:
races = data['race'].unique().tolist()

In [41]:
for i in races:
    print('Impact ratio between White and {}'.format(i),impact_ratio('race',i,'White'))

Impact ratio between White and White (1.0, 1.0)
Impact ratio between White and Black (0.47565882219299216, 2.1023472147317044)
Impact ratio between White and Asian-Pac-Islander (1.0601181117243244, 0.9432911191126243)
Impact ratio between White and Amer-Indian-Eskimo (0.4607374896946818, 2.170433321288165)
Impact ratio between White and Other (0.4848782359079723, 2.0623734495474353)


### Mean Difference


$$d = p(y^{+}|s^{0}) - p(y^{+}|s^{1})$$

In [42]:
def mean_difference(column, protected, general):
    p_f = data[data[column] == protected]['target'].sum()/data[data[column] == protected].shape[0]
    p_m = data[data[column] == general]['target'].sum()/data[data[column] == general].shape[0]
    d = p_m - p_f
    return d

In [43]:
mean_difference('sex','Female','Male')

0.19451574596420296

In [44]:
for i in races:
    print('Mean difference between White and {}'.format(i),mean_difference('race',i,'White'))

Mean difference between White and White 0.0
Mean difference between White and Black 0.13317577877014827
Mean difference between White and Asian-Pac-Islander -0.015269211509504055
Mean difference between White and Amer-Indian-Eskimo 0.1369656014273385
Mean difference between White and Other 0.13083416866347725


### Normalized difference

In [45]:
def normalized_difference(column,protected,general):
    d = mean_difference(column,protected,general)
    pypos = data[data['target'] == 1].shape[0]/data.shape[0]
    pyneg = data[data['target'] == 0].shape[0]/data.shape[0]
    ps1 = data[data[column] == protected].shape[0]/data.shape[0]
    ps0 = data[data[column] == general].shape[0]/data.shape[0]
    d_max = min((pypos/ps0),(pyneg/ps1))
    return d/d_max

In [46]:
normalized_difference('sex','Female','Male')

0.5434191071901452

In [47]:
normalized_difference('race','Black','White')

0.47588661529895887

In [48]:
for i in races:
    print('Impact ratio between White and {}'.format(i),normalized_difference('race',i,'White'))

Impact ratio between White and White 0.0
Impact ratio between White and Black 0.47588661529895887
Impact ratio between White and Asian-Pac-Islander -0.05456257474629147
Impact ratio between White and Amer-Indian-Eskimo 0.48942906193278946
Impact ratio between White and Other 0.4675191710211463


### Area under the curve (AUC)

In [49]:
#Too expensive, don't try it :'v
def auc():
    men = data[data['sex'] == 'Male']
    women = data[data['sex'] == 'Female']
    suma = 0
    for i,row in men.iterrows():
        for j,row2 in women.iterrows():
            if row['target'] > row2['target']:
                suma +=1
    return suma/(men.shape[0]*women.shape[0])

### Elift ratio

In [50]:
def elif_ratio2(column,protected,general):
    p_g = data[(data[column] == general)&(data['target'] == 1)].shape[0]
    r = p_g/data[data['target'] == 1].shape[0]
    return r

In [51]:
def elif_ratio(column,protected,general):
    p_g = data[data[column] == general]['target'].sum()
    r = p_g/data[data['target'] == 1].shape[0]
    return r

In [52]:
elif_ratio('sex','Female','Male')

0.8486352357320099

In [53]:
elif_ratio2('sex','Female','Male')

0.8486352357320099

In [54]:
for i in races:
    print('Impact ratio between White and {}'.format(i),elif_ratio2('race',i,'White'))

Impact ratio between White and White 0.9075896295028665
Impact ratio between White and Black 0.9075896295028665
Impact ratio between White and Asian-Pac-Islander 0.9075896295028665
Impact ratio between White and Amer-Indian-Eskimo 0.9075896295028665
Impact ratio between White and Other 0.9075896295028665


In [55]:
from sklearn.naive_bayes import GaussianNB

In [56]:
m_NB = GaussianNB()
m_NB.fit(X_train,y_train)

GaussianNB()

In [57]:
y_pred = m_NB.predict(X_test)

In [58]:
accuracy_score(y_test,y_pred)

0.7957127940544193

In [59]:
def fairness_metrics(y_pred,y_true):
    """Calculate fairness for subgroup of population"""
    
    #Confusion Matrix
    cm=confusion_matrix(y_true,y_pred)
    TN, FP, FN, TP = cm.ravel()
    
    N = TP+FP+FN+TN #Total population
    ACC = (TP+TN)/N #Accuracy
    TPR = TP/(TP+FN) # True positive rate
    FPR = FP/(FP+TN) # False positive rate
    FNR = FN/(TP+FN) # False negative rate
    PPP = (TP + FP)/N # % predicted as positive
    
    return np.array([ACC, TPR, FPR, FNR, PPP]) 

In [60]:
fairness_metrics(y_pred,y_test)

array([0.79571279, 0.3049922 , 0.05251307, 0.6950078 , 0.11215527])

In [61]:
pipeline = Pipeline([('scaler',StandardScaler()),('log',LogisticRegression(penalty='l1',C = 0.1,solver='saga',max_iter=400))])

#log = LogisticRegression(penalty='l1',C = 0.1,solver='saga',max_iter=400)
pipeline.fit(X_train,y_train)

c:\Users\Beate\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


Pipeline(steps=[('scaler', StandardScaler()),
                ('log',
                 LogisticRegression(C=0.1, max_iter=400, penalty='l1',
                                    solver='saga'))])

In [62]:
y_pred = pipeline.predict(X_test)

In [63]:
accuracy_score(y_test,y_pred)

0.85283459246975

In [64]:
fairness_metrics(y_pred,y_test)

array([0.85283459, 0.59672387, 0.06795336, 0.40327613, 0.19286285])

In [65]:
y_pred

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [66]:
y_pred_males = y_pred[X_test[X_test['sex_Male'] == 1].index.tolist()]
y_pred_females = y_pred[X_test[X_test['sex_Male'] == 0].index.tolist()]

In [67]:
y_test_males = y_test.loc[X_test[X_test['sex_Male'] == 1].index]
y_test_females = y_test.loc[X_test[X_test['sex_Male'] == 0].index]

In [68]:
fm_sex_1 = fairness_metrics(y_pred_males,y_test_males)
fm_sex_0 = fairness_metrics(y_pred_females,y_test_females)

In [69]:
fm_sex = fm_sex_0/fm_sex_1

In [70]:
fm_sex

array([1.14045264, 0.858641  , 0.21849343, 1.22105432, 0.30255426])

In [71]:
fm_sex_0

array([0.92916436, 0.52372881, 0.02132064, 0.47627119, 0.07600074])

In [72]:
fm_sex_1

array([0.81473297, 0.60995086, 0.09758022, 0.39004914, 0.25119705])

In [74]:
# classify data
clf =   DecisionTreeClassifier(max_depth=10)
clf.fit(X_train, y_train)
pred_Y = clf.predict(X_test)

# scores
print(precision_recall_fscore_support(y_test, pred_Y, average="macro"))
print(precision_recall_fscore_support(y_test, pred_Y, average="micro"))
accuracy_score(y_test, pred_Y)

(0.8219634197920687, 0.7687117786279605, 0.7897690943474325, None)
(0.8602665683926048, 0.8602665683926048, 0.8602665683926048, None)


0.8602665683926048

## Calculate the consistency measure

In [75]:
# we use sklearn to find the nearest neighbors
neigh = NearestNeighbors(n_neighbors=10)
nbrs = neigh.fit(X_test)
distances, indices = nbrs.kneighbors(X_test)

In [76]:
# calculate C
sum = 0
for i in range(len(indices)):
    for j in range(10):
        sum += np.abs(int(pred_Y[i])-int(pred_Y[indices[i][j]]))
result = 1 - sum*(1/(10*len(indices)))
print(result)

0.786407468828696
